development:
  :host: localhost
  :port: 6379
  :db: 2

testing:
  :host: localhost
  :port: 6379
  :db: 2

production:
  :host: localhost
  :port: 6379
  :db: 2

test:
  :host: localhost
  :port: 6379
  :db: 2
